#+TITLE: Macroeconomics notes
:LOGBOOK:
- Note taken on [2018-01-29 Mon 22:15] \\
  ECON 102 at University of Alberta - Andrew Wong
- Note taken on [2018-01-08 Mon 15:37] \\
  По мотивам курса ВШЭ на Coursera (Олег Замулин)
:END:
* Тема 1: Введение в макроэкономику, история макроэкономической мысли.
Первая тема курса посвящена истории макроэкономической науки, основным
теориям, которые имели место за время ее существования, а также
ситуации,которая сложилась на сегодняшний день.

- до 1930х не было разделения на микро и макро-экономику
  - великая депрессия
    - опровергала классическую теорию
- John Maynard Keynes
  - доминирование стороны совокупного спроса
  - отклонения от конкурентного равновесия
    - медленно подстраивающиеся цены и зарплаты
    - неполнота информации
      - банки не знают, кому можно давать кредиты
      - вкладчики не знают, где хранить сбережения
- Сторона спроса подвержена колебаниям
  - animal spirits of investors
  - надо искусственно увеличить спрос
    - понизить процентную ставку
  - бюджетные меры
    - повысить расходы государства
    - New Deal
    - военные расходы после начала войны
  - регулирование рынка
    - система страхования банковских вкладов
- Монетаризм: Милтон Фридман & Anna Schwartz
  - важность денежной политики
  - золотой стандарт
    - доверие к деньгам из-за обеспеченности золотыми резервами
    - золото утекало из стран с торговыми дефицитами в страны с торговыми профицитами
      - продажа облигаций для того чтобы стерилизовать деньги
      - глобальная дефляция
        - Франция и США имели торговые профициты
          - подняли процентные ставки
        - остальные страны так же подняли ставки, чтобы удержать золото
          - дорожание кредита
          - дефляция 11% в ]929 году
  - выход из золотого стандарта
    - Ben Bernanke, Essays on the Great Depression, 2000
  - дефляция ведет к росту реальных зарплат
    - высокие процентные ставки
      - при дефляции 10% реальные ставки не могут быть меньше 10%,
        даже при нулевой номинальной ставке
  - банковские призисы
- Кривая Филлипса
  - отрицательная связь между инфляцией и безработицей
  - Никсон призвал увеличить инфляцию, чтобы уменьшить безработицу
    - план удался наполовину: ифляция выросла
    - великая стагфляция
  - гипотеза Фридмана-Фелпса
    - естественный уровень безработицы
      - определяется структурой экономики
        - фрикционный уровень
        - стимулируящая безработица
      - невозможно понизить стимулированием спроса
        - противоречит кейнсианской теории
        - мико обоснования важны в макро!
- классическая дихотомия
  - номинальные переменные не могут менять реальные в долгосрочной
    перспективе
  - неожиданное увеличение денежной массы ведет к временному буму и
    инфляции (отсюда кривая Филлипса)
  - _ожидаемое_ увеличене денежной массы ведет только к инфляции
- кривая Филлипса существовала пока не было денежной политики
  - рациональные ожидания
- возвышение монетаризма
  - 1980-82: остановка роста денежной массы
    - самая глубокая рецессия в США
- теория реальных экономических циклов (real business cycle, RBC)
  - равновесие достигается быстро
  - рецессии и бумы связаны с реальными шоками (технологическими прорывами и тп)
  - сторона спроса наважна
    - стабилизационная политика не нужна
  - шоки со стороны предложения
    - протекционизм
    - усиление профсоюзов
    - ослабление антимонопольных законов
- новые кейнсианцы
  - рынок долго приходит в равновесие
  - важна сторона спроса
  - ожидания играют ключевую роль
  - микроэкономическое обоснование жесткости цен
  - стабилизационная политика должна быть денежной
- стерлись различия между кейнсианством и монетаризмом
  - деньги влияют только на инфляцию
    - выпуск задается только стороной предложения
  - в краткосрочной перспективе, деньги влияют на реальные переменные
    - из-за медленного изменения цен
  - есть роль для стабилизационной денежной политики
* Тема 2: Система национальных счетов: ВВП, безработица, инфляция.
Вторая тема курса посвящена системе национальных счетов и основным
макроэкономическим понятиям – ВВП, безработице и инфляции. Обсуждаются
их определения, методы статистической оценки, а также их значимость и
недостатки.

- Основные понятия макроэкономики
  - ВВП
  - инфляция
  - безработица
- ВВП
  - размер экономики
  - _стоимость_ _всех_ _конечных_ товаров и услуг, произведенных
    _в границах_ государства в течение определенного _периода_
    - рыночная стоимость
      - не все товары и услуги производятся по рыночным ценам, или
        вообще продаются
      - относительная цены могут меняться при фиксированным физическом производстве
        - относительная стоимость во многом субъективна
      - армейские услуги не продаются по рыночным ценам
      - аренда квартир учитывается, а проживание в собственном доме нет
      - цены на монополизированных рынках завышенны
    - внутри страны
      - когда Тойота производит автомобиль в России, его стоимость
        идет в ВВП России, но в ВНП Японии
    - за единицу времени
      - потоковая величина, не запасовые (как богатство или капитал)
    - конечные товары
      - если сталь использовали для производства автомобиля, в ВВП
        входит только стоимость автомобиля
        - если сталь произвели в 2012 году, а использовали в 2013, то
          в 2012 году стоимость стали учитывается, но вычитается из
          ВВП 2013го
  - ВВП - мера производства
    - lawn mowing
    - сизифов труд тоже учитывается в ВВП
    - не мера благосостояния
      - не учитывает накопленное богатство
      - не учитывает время отдыха
      - не учитывает экологию
      - не учитывает образование и духовное развитие
      - не учитывает равенство
    - IMF World Economic Outlook
    - PPP: purchasing power parity - паритет покупательной способности
    - Вычисление ВВП по использованию (Кейнсианский взгляд)
      - Y = C + I + G + NX
      - I (не финансовые) инвестиции!
        - закупка основных фондов
        - строительство жилья
        - накопление запасов
          - желаемые и нежелаемые инвестиции
          - индикатор деловой активности
      - госрасходы
        - трансферные платежи не входят
        - пенсии, пособия
      - ВВП России 2013
        - C = 51.66%, I = 23%, G = 19.5%, NX = 5.64% = 28.26% - 22.62%
      - ВВП по доходу: всё, что кем-то заплачено, кем-то заработано
        - Y = сумма доходов в экономике
          - трудовые зарплаты: зарплаты, бонусы, прибыль
          - доходы от капитала: прибыль, дивиденды, аренда
          - косвенные налоги на продукт: акцизы, налог с продаж, ...
          - выбытие капитала (амортизация)
          - вычитаем зарубежные доходы
          - добавляем доходы иностранцев внутри страны
      - ВВП как добавленная стоимость
        - вклад автомобиля в ВВП: автомобиль = (автомобиль - сталь) + (сталь - руда) + (руда)
    - реальный и номинальный ВВП
      - можно считать ВВП в ценах базового года
        - как считать стоимость современных компьютеров в ценах 1980 года?
      - часто меняют базовый год - каждые 5 лет
      - цепной индекс: считаем прирост ВВП как среднее из прироста в
        году N и N+1
- инфляция = рост цен
  - _общий_ рост цен, изменение _относительных_ цен не учитывется
  - общий уровень цен не наблюдаем
    - индексы
      - ИПЦ: индекс потребительских цен
        - стоимость реперзентативной потребитьельской корзины
        - можно считать для разных групп населения
      - дефлятор ВВП = (номинальный ВВП)/(реальный ВВП)
        - изменение цен всех товаров и услуг, произведенных в этом году
        - многие товары не имеют значения для населения
      - индекс цен производителей
        - оптовые цены от производителя, по отдельным отраслям
  - общие проблемы:
    - трудно учитывать изменение качества товаров
    - появление новых товаров
  - проблемы ИПЦ
    - не учитывает замещение дорогих товаров дешевыми
      - переоценивает инфляцию
      - Boskin report 1996
    - проблемы дефлятора ВВП
      - слишком сильно учитывает замещение
        - недооценивает инфляцию
      - учитывает многие "неважные" товары и услуги
- безработица
  - доля экономически активное населения без работы
    - те, кто хотят работать но не могут найти место
    - при выходе из кризиса многие начинают искать работу, но пока не
      могут найти - в итоге безработица может сначала расти
  - измерение по технологии международной организации труда
    - did not work at all in the previous week
    - were available to work if they had been offered a job
    - were making efforts to look for a job
  - фрикционная безработица
  - структурная безработица
    - технический прогресс или международная торговля лишает смысла
      целую профессию
  - цикличная безработица
    - возникает во время спада, когда спрос в экономике недостаточен
** Тест 2
- National income is defined as
  - the total income earned by a nation's residents from the
    production of goods and services within the borders of the
    country
- A country reported nominal GDP of $200 billion in 2012 and $180
  billion in 2011 and reported a GDP deflator of 125 in 2012 and 105
  in 2011. What happened to real output and prices from 2011 to 2012?
  - 2012: $200B/125 = $1.6B
  - 2011: $180B/105 = $1.71B, so real output fell
  - (prices in 2012)/(prices in 2011) = 125/105 > 1, so prices rose
- In 2007, Freedonia had a population of 2,700 and real GDP of about
  1,080,000. In 2006 it had a population of 2,500 and real GDP of
  about 1,000,000. What was the approximate growth rate of real GDP
  per person in Freedonia between 2006 and 2007?
  - (1080/27)/(1000/25) = 40/40 = 1, so 0% growth
- Ethel purchased a bag of groceries in 1970 for $8. She purchased the
  same bag of groceries in 2006 for $25. If the price index was 38.8
  and is 180 in 2006, what's the price of a 1970 bag of groceries in
  2006 prices?
  - $8×180/38.8 = 37.11
- If a country reported a nominal GDP of 85 billion in 2007 and 100
  billion in 2006 and reported a GDP deflator of 100 in 2007 and of
  105 in 2006, then from 2006 to 2007 real output
  - output fell from 2006 to 2007:
    - 2007: $85B/100 = $.85B
    - 2006: $100B/105 = $.95B
  - prices: 100/105 < 1, so prices fell
- By itself a reduction in the price of large tractors imported into
  Canada from Russia will
  - will not change either the GDP deflator or the consumer price
    index
- The price index in the first year is 125, in the second year is 150,
  and in the third year is 200. What is the inflation rate between the
  first and second year and between the second and third year?
  - 150/125 = 1.2, 200/150 = 1.3(3)
- Рассмотрим открытую экономику страны A, в которой потребление
  составляет 2/3 от валового внутреннего продукта. Кроме того,
  известно, что инвестиции составляют 1/9 от валового внутреннего
  продукта, а государственные закупки меньше инвестиций на 10 млрд
  долларов. Наконец, также известно, что экспорт превышает импорт на
  25 млрд долларов. На основании приведенных данных рассчитайте объем
  валового внутреннего продукта страны A в млрд долларов.
  - Y = C + G + I + NX = 2Y/3 + (Y/9 - 10) + Y/9 + 25
  - Y/9 = 15
  - Y = 135
- В 2010 году экономически активное население страны A составляло 100
  млн человек, из которых 95 млн имели работу. В течение следующих
  четырех лет состав экономически активного населения покинули 2 млн
  занятых и 1 млн безработных, но, с другой стороны, за этот же период
  состав экономически активного населения пополнили 9.3 млн человек,
  которые получили работу, и 3.7 млн безработных. Определите, на
  сколько процентных пунктов уровень безработицы в 2014 году больше
  аналогичного показателя в 2010 году
  - 2010: (100-95)/100 = 5%
  - 2014: (5 - 1 + 3.7)/(100 - 2 - 1 + 9.3 + 3.7) = 7.7/110 = 7%
  - разница: 7% - 5% = 2%

- Предположим, что совокупный выпуск страны состоит из двух видов
  товаров. На основе приведенной таблицы рассчитайте реальный ВВП (в
  млрд рублей) в 2013 году, считая 2012 год базисным.
  |------------------+----------------+----------------+----------------+----------------|
  |                  | 2012 - товар 1 | 2012 - товар 2 | 2013 - товар 1 | 2013 - товар 2 |
  |------------------+----------------+----------------+----------------+----------------|
  | цена, руб        |             10 |             15 |             12 |             20 |
  | выпуск, млрд. шт |            2.5 |              2 |              3 |              2 |

  - Реальный ВВП в 2013 - это ВВП в ценах 2012 (базисного) года
     =  ₽10 * 3 млрд + ₽15 * 2 млрд = ₽60 млрд
* Тема 3: Равновесие на рынке труда и рынке заемных средств. Общее равновесие.
Третья тема курса посвящена равновесию на рынке труда и рынке заемных
средств, а также понятию общего равновесия. Обсуждается определение
уровня производства в «идеальном» случае, при полном использовании
всех имеющихся ресурсов, а также распределение этого продукта по
экономике.

- моделирование ВВП
  - функция производства Y = A × F(K,L)
    - K капитал (основные фонды)
    - L рабочая сила
    - A общефакторная производительность (уровень технологии)
  - классическое предположение - постоянная отдача от масштаба
    - F(αK,αL) = α F(K,L)
  - уменьшающийся предельный продукт
    - по мере увеличеня количества одного из факторов его предельный
      продукт уменьшается
  - взаимодополняемость факторов
    - увеличение другого фактора увеличивает предельный продукт
  - функция Кобба-Дугласа
    - $Y = A × K^α L^β$
      - для развитых стран, $α = 0.3, β = 0.7$
      - для России, $α = 0.5$
      - коэффициент α - доля доходов капитала в ВВП, β - доля трудовых
        доходов
      - L можно наблюдать из данных
      - K наблюдать сложнее
        - балансовая оценка основных фондов
        - или сумма прошлых инвестиций
      - наблюдаем Y, можем вычислить A для каждого периода времени
- капитал - запасовая переменная
  - накапливается в результате инвестиций
  - выбывает из-за износа (физического и морального)
  - чтобы существенно изменить капитал, нужны годы
    - единственным источником _краткосрочных_ колебаний выпуска может служить L
      - или колебания ее производительности
- рынок L
  - потоковая переменная (человеко-часы)
  - спрос и предложение - функции цены (реальной зарплаты)
    - спрос на рабочую силу (LD, labor demand)
      - MPL должен превышать W/P
        - MPL (marginal product of labor) предельный продукт труда
        - W wage level, P price level
      - чем меньше рыночная зарплата, тем меньше фирмы готовы нанимать
      - изменение зарплаты не влияет на спрос - движение по кривой спроса
      - увеличение спроса - сдвиг кривой вправо
        - например, из-за увеличения A или K
    - предложение рабочей силы
      - максимизирует полезность
        - выбор между больше потреблять и больше отдыхать
      - предельная полезность от отдыха vs от рабочего часа
      - если зарплата вырастает
        - отдых становится дороже
        - с другой стороны, индивид может позволить себе больше отдыхать
        - эмпирически, чем выше зарплата, тем больше предложение труда
  - равновесие на рынке труда
  - жесткие зарплаты - циклическая безработица
- Капитал
  - процесс накопления капитала: ΔK = I - δK
    - δ - норма выбытия (амортизация)
  - надо понять, как определяются инвестиции
  - сбережения S = Y - C - G
  - представим как сумму частных и гос сбережений:
    - S = Y - C - G = (Y - C - T) + (T - G)
      - T = taxes
      - (T - G) = профицит гос бюджета
  - случай закрытой экономики (NX=0): Y = C + I + G ⇒ S = I
    - почему инвестиции равны сбережениям - это ведь решения разных игроков?
    - рынок заемных средств
      - фирмы готовы брать в долг и инвестировать, если предельная
        отдача от капитала MPK больше реальной процентной ставки r
      - если S > I, банки понизят процентные ставки - тогда фирмы
        будут больше занимать, а население меньше депозировать
- общее равновесие
  - национальный доход производится из
    - равновесной рабочей силы L
    - накопденного капитала K
    - уровня технологии A
- распределение дохода
  - трудовые доходы
  - доходы капитала: аренда, лизинг, большая часть бухгалтерской
    прибыли фирмы на конкурентном рынке
  - (сверх-) прибыль монополистических фирм
** Домашнее задание: Тест 3.
- Экономика страны B описывается производственной функцией
  Кобба-Дугласа: $Y = AK^{\alpha}L^{1-\alpha}$. Параметр общефакторной
  производительности равен $2.5$. Доля дохода капитала в ВВП
  составляет $0.5$. Функция спроса на рынке труда имеет вид
  $L^D=500-10w$, функция предложения труда – $L^S=10w+300$ ($w$ –
  реальная заработная плата). Запас капитала в экономике составляет
  $100$. Рассчитайте национальный доход экономики страны B.
  - L = 10w + 300 = 500 - 10w
    - w = 10
    - L = 400
  - \alpha = 1/2
  - Y = (5/2) × (100 × 400)^(1/2) = 500
* Тема 4: Экономический рост.
Четвертая тема курса посвящена тенденции экономик расти в течение
десятилетий и веков. Обсуждается механизм экономического роста
посредством накопления физического капитала и технического прогресса,
а также институциональные условия, необходимые для устойчивого роста.

- ВВП производится из ресурсов, с учетом уровня технологии
- чтобы ВВП рос, нужно, чтобы расли K, L, A
- почему растет рабочая сила?
  - растет по естественным причинам - растет население
    - квалификация труда учитывается как человеческий капитал (K) или
      технология (A)
    - L на человека не изменялся последние 100 лет
  - страны с быстрым ростом населения растут медленно
    - скорее, обратная зависимость: в бедных странах большие семьи -
      пенсионная система
- рост K: модель роста Солоу (Solow)
  - богатые страны богаты потому, что больше инвестируют?
    - как этого добиться?
  - пока капитала мало, свободной рабочей силы много, производство растет
  - выбытие капитала растет пропорционально количеству, а его средняя
    производительность падает (уменьшающийся MPK)
  - предположим, что K растет, а L - нет, и технического прогресса
    тоже нет
    - Y = F(K) = C + I
    - сберегаем и инвестируем долю s: I = s × F(K)
    - капитал выбывает со скоростью δ
    - динамика капитала ΔK = I - δK = s × F(K) - δK
      - F''(K) < 0
      - фазовая диаграмма
    - равновесие s × F(K) = δK
      - не оптимум - просто точка, в которой экономика перестает расти
  - азиатское чудо
    - также послевоенная Германия и Япония
    - развивающиеся страна _должна_ расти быстрее чем развитая
- сбережения и рост:
  - норма накопления в большинстве азиатских стран - более 30% ВВП. В
    России - около 20%.
  - новое стационарное состояние будет иметь больший ВВП и больший
    капитал
  - эффект временный
  - догоняющий рост ускоряется
  - больший ВВП не обязательно хорошо
    - для людей важно максимизировать C, а не Y
    - надо найти уровень сбережений, при котором стационарное
      потребление максимально
    - эмпирически, большинство стран сберегают слишком мало
- инвестиции и сбережения делаются разными игроками
- инвестиции делаются, когда это выгодно и безопасно
  - налоговые вычеты
  - устранение бюрократических барьеров
  - развитие инфраструктуры
  - защита прав инвесторов, судебная система
- как сделать так, чтобы люди меньше тратили и больше сберегали
  - устойчивая финансовая система
  - накопительная пенсионная система
  - налогообложение потребления, а не дохода
- технический прогресс. стационарный рост
  - накопление капитала имеет ограниченный эффект на рост
  - технический прогресс позволяет работникам использовать больше
    оборудования
    - больше капитала при той же рабочей силе
    - перепишем модель Солоу: Y = F(K, EL), где E растет
    - стационарный рост: постоянное количество капитала на
      "фактического" работника
    - дополнительные машины позволяют нанять освободившуюся рабочую
      силу
- экономический рост в СССР
  - модель Солоу не требует предположения о рыночной экономике
    - решения об ивестиции могут делаться госпланом
    - модель предписывает эффект от инвестиций, не их причины
  - замедление роста в 1970х (Ofer 1987)
    - рост шел за счет L и K, очень мало за счет E
    - L: закон об обязательной трудовой повинности
      - к 1980-м ресурс иссяк
    - K: инвестиции в среднем 7.3% в год
      - в основном в тяжелую промышленность
      - в основном в новое оборудование, мало в модернизацию старого
    - E: мало стимулов к инновациям
      - мало технологий внедрялось
      - 1985 - ускорение
- недостатки модели Солоу
  - модель не учитывает стимулы
  - что источник роста? почему экономики растут?
  - почему рост есть не везде?
  - институциональная экономика
  - стимулы в развитых странах: почему растет E?
    - производители стараются сделать производство более эффективным
    - работники пытаются научится работать лучше
    - проблема безбилетника
      - патентование
      - авторские права
    - гос финансирование науки и инноваций?
      - аргумент в пользу плановой экономики
  - стимулы в развивающихся странах: инновации или имитация?
    - развивающиеся страны еще не используют все технологии
      - имеет смысл учиться у других
      - покупать лицензии, обучение, прямые иностранные инвестиции
    - промышленный шпионаж, пиратское ПО
** Тест 4
- Inward-oriented policies
  - in some ways are like prohibiting the use of certain technologies
- If a country's saving rate increases, in the long run
  - neither productivity growth nor income growth increase
- Suppose that there are diminishing returns to capital. Suppose also
  that two countries are the same except one has less capital and so
  less real GDP per person than the other. Finally, suppose that the
  saving rate in both countries increases from 5 percent to 6
  percent. Over the next ten years we would expect that
  - the country with less capital will grow faster
* Тема 5: Международная макроэкономика: торговля, потоки капитала, обменные курсы.
Пятая тема курса посвящена основным понятиям международной
макроэкономики: торговле, потокам капитала и обменным
курсам. Обсуждаются макроэкономические аспекты международной торговли
и потоков капитала, а также базовые причины изменений обменных курсов.

- открытая экономика
- NX > 0: страна произвела: но не приобрела
  - NX = balance of trade
    - NX < 0: trade deficit
    - NX > 0: trade surplus
- с другой стороны, то, что страна заработала, но не потратила,
  она должна дать в долг за рубеж
- торговые дефициты и движение капиталов - две стороны одной медали
- торговля в пространстве и времени
  - в пространстве: каждая страна продает то, в чем у нее есть
    сравнительное преимущество
  - во времени: потребление (инвестиции) сегодня важнее, чем
    утраченное потребление (инвестиции) завтра
    - NX = S - I
      - чтобы купить что-либо, надо либо продать что-либо, или занять
        за рубежом
    - платежный баланс
      - счет текущих операций
        - NX + дивиденды от капитала за рубежом
      - счет движения капитала
        - все иностранные инвестиции и займы
          - прямые инвестиции (FDI, foreign direct investment) или займы
          - портфельные инвестиции (FPI, foreign portfolio investment)
    - профицит по текущему счету означает отток капитала
      - NCO, net capital outflow
      - balance-of-payments identity: NX = NCO
      - страна не может одновременно быть чистым экспортером товаров и
        чистым импортером капитала
  - глобальный дисбаланс 2000х
    - развитые страны (США) имеют очень малые или отрицательные сбережения
      - NX = S - I < 0
    - Азиатские страны и Россия дают в долг!
    - центробанки скупают валютную выручку и покупают на нее
      американские облигации
  - как достигается равновесие?
    - номинальный курс e - цена одной валюты в другой
      - цена доллара в рублях
    - реальный обменный курс $ε = e \frac{P}{P^*}$
      - P^* - уровень цен за рубежом, P - домашний уровень цен
    - реальный эффективный обменный курс
      - относительно корзины валют торговых партнеров
- реальный курс и платежный баланс
  - сторона спроса: если ε падает, то домашние товары становятся более
    дешевыми
    - вырастает экспорт и падает импорт
      - $\frac{d\,NX}{d ε} < 0$
        - это только сторона спроса!
          - девальвация сама по себе не обязательно ведет к росту!
  - сторона предложения
    - NX = S - I
      - реальный курс подстраивается так, чтобы привести к равенству
- модель "малой" открытой экономики
  - цены и процентные ставки определяются на мировом рынке
  - совершенная мобильность капитала
    - реальная ожидаемая кредитная ставка $r^*$ единая во всем мире
  - потребление C задано
    - $S = Y - C - G$ не зависят от $r$
  - I = I(r)
    - реальная ставка r теперь мировая, определяется мировыми
      сбережениями и инвестициями
  - NX определяются только нашим желанием сберегать и
    инвестировать
  - Выпуск: Y = A × F(K,L)
    - Предположим, что потребление C задано и не зависит от $r^*$
    - Спрос на инвестиции определяется (мировой)
      реальной процентной ставкой: I=I(r)
    - Определяем NX от r:
      #+BEGIN_SRC latex :file /tmp/ggg.pdf :packages '(("" "tikz")) :results raw
        \usetikzlibrary{decorations.pathreplacing}
        \begin{tikzpicture}[
            scale=5,
            axis/.style={very thick, ->, >=stealth'},
            important line/.style={thick},
            dashed line/.style={dashed, thin},
            pile/.style={thick, ->, >=stealth', shorten <=2pt, shorten
            >=2pt},
            every node/.style={color=black}
            ]
            % axes
            \draw[axis] (-0.1,0)  -- (1.1,0) node(xline)[right]
                {$I,S$};
            \draw[axis] (0,-0.1) -- (0,1.1) node(yline)[above] {$r$};
            % Lines
            \draw[important line] (.75,0.0) coordinate (A)
                               -- (.75,.85) coordinate (B)
                  node[centre, text width=8em] {$S=Y-(C+G)$};
            \draw[important line] (.05,.85) coordinate (C)
                               -- (.95,.05) coordinate (D)
                  node[right, text width=5em] {$I(r)$};
            \draw[dashed line]     (0,.6)   coordinate (E)
                                -- (1.,0.6) coordinate (F)
                  node[above, text width=5em] {$r^*$};
            % Intersection of lines
            \fill[red] (intersection cs:
               first line={(A) -- (B)},
               second line={(C) -- (D)}) coordinate (G) circle (.4pt)
               node[right,] {$r_{\rm closed}$};
            \fill[blue] (intersection cs:
               first line={(E) -- (F)},
               second line={(C) -- (D)}) coordinate (K) circle (0.3pt)
               node[above,] {$I(r^*)$};
            \fill[blue] (intersection cs:
               first line={(E) -- (F)},
               second line={(A) -- (B)}) coordinate (L) circle (0.3pt)
               node[below,] {$$};
            \draw [decorate, decoration={brace}, yshift=4ex] (K) --  node [above,] {NX} (L);
        \end{tikzpicture}
      #+END_SRC

      #+RESULTS:
      [[file:/tmp/ggg.pdf]]
    - добавим сторону спроса: $NX = NX(ε) = S - I(r^*) = A × F(K,L) - (C + G + I(r^*))$
      - ε - это относительная цена товаров, и является результатом
        равновесия
        - фундаментальный реальный курс - долгосрочное равновесие
      - график ε vs NX
        - чистый экспорт определяется S и I - кривая определяется
          предпочтениями экспорта/импорта
        - реальный курс подстраивается так, чтобы именно столько
          импортировать и экспортировать
    - Пример: увеличение оптимизма
      - предположим, что I увеличивается (отдача от капитала больше)
      - порождает спрос на рубли (в реальных величинах, растет спрос
        на товары и L)
        - растёт реальный курс ε
        - импорт растет, экспорт падает: NX ↘
        - отток капитала S-I и чистый экспорт NX оба упали
        - на графике: I(r) сдвигается вправо, ε растет
    - Пример: глобальный дисбаланс между США и Азией
      - У США S мал, I большой
      - ограничивают предложение долларов на мировом рынке
        - американские товары дорогие
        - Из S-I < 0 следует NX < 0, и ε растёт
    - график реального курса и текущего счета США
** Тест 5
- Across countries, investment and growth rates are
  - positively related
- Производственная функция экономики задается как F(K,L)=K⋅L, а выпуск
  определяется как Y=AF(K,L). Запас капитала в экономике равен 40,
  рабочая сила равна 25, параметр общефакторной производительности
  равен 2. Также известно, что объем совокупного потребления
  составляет 1300, а государственные закупки – 300. Уравнение спроса
  на инвестиции имеет вид I=500−25r∗ (ставка r∗ измеряется в
  процентных пунктах). При какой мировой процентной ставке r∗ чистый
  экспорт данной страны будет равен 50?
  - S = Y - (C + G) = I + NX = NX + 500 - 25r
    ∴ r = 20 + (NX + C + G - Y)/25 = 20 + ( NX + C + G - A✕K✕L )/25 = 6
- Если национальные сбережения страны составляют 10 трлн рублей,
  инвестиции – 7 трлн рублей, а государственные закупки – 4 трлн
  рублей, то какие из нижеприведенных утверждений верны?
  - NX = S - I = 10 - 7 = 3
  - Y = C + G + NX + I, so Y - C = G + NX + I = G + S = 4 + 10 = 14
- Известно, что величина экспорта страны составляет 12 трлн рублей, а
  импорта – 8 трлн рублей. Кроме того, дивиденды от капитала за
  рубежом равны 0. Какой из нижеперечисленных вариантов верно
  характеризует состояние счета движения капитала данной страны?
  - CF + NX = 0, so CF = - (12-8) = -4
- В каких из перечисленных случаев российские товары становятся
  относительно дороже американских товаров?
  - напоминание: $ε = e \frac{P}{P^*}$
  - Уровень цен в России и номинальный курс увеличиваются на 50%, а
    уровень цен в США остается на неизменном уровне.
  - Уровень цен в России растет, а номинальный курс и уровень цен в
    США остаются неизменными.
  - Уровень цен в США падает, а уровень цен в России возрастает при
    неизменном значении номинального курса.
- На каком графике изображены последствия увеличения
  производительности капитала?
* Тема 6: Финансовые рынки.
Шестая тема курса посвящена финансовым рынкам. Обсуждается, как должна
работать финансовая система, и почему она может давать сбои.

- роль финансовых рынков
  - сбережения превращаются в инвестиции
  - финансовая система направляет средства между S и I
    - просчеты финансовой системы - одна их главных причин
      экономических кризисов
- механизмы финансирования инвестиций
  - реинвестирование доходов
  - кредиты и займы
    - банк выступает как финансовый посредник
      - принимает сбережения у граждан и дает в долг фирмам
      - работа банка - определить, кому можно давать в долг, а кому
        нет
    - выпуск облигаций
      - нет посредников
        - кредит получается дешевле
      - доступно только крупным фирмам
  - эмиссионное финансирование
    - АО: выпуск акций и продажа на открытом рынке
    - покупатели акций становятся совладельцами
    - доля существующих акционеров размывается
- акции торгуются на фондовой бирже
  - В России - ММВБ, московская международная валютная биржа
  - сигнальная роль цен на акции
  - условие отсутствия арбитража: $q_{t+1}-q_t + d_{t+1} = r q_t$
    - q_t - цена акции в момент t, d_t - дивиденд по акции, r -
      процентная ставка
    - ожидаемая доходность по акции должна равняться процентной ставке
    - $q_t =  \frac{q_{t+1} + d_{t+1}}{1+r}$
      - приведенная стоимость будущей цены акции и дивиденда
      - дисконтированные будущие доходы
    - $q_t = \lim_{k\to\infty} \frac{q_{t+k}}{(1+r)^k}
             \ + \sum_{k=0}^\infty \frac{d_{t+k}}{(1+r)^k}$
      - $\lim_{k\to\infty} \frac{q_{t+k}}{(1+r)^k}$ называется пузырём
      - $\sum_{k=0}^\infty \frac{d_{t+k}}{(1+r)^k}$ - фундаментальная
        стоимость акции
    - теорема Модильяни-Миллера: приведенная стоимомть дивидендов
      равна приведенной стоимости прибылей
- Q-терия Тобина (James Tobin)
  - фирма инвестирует, если ее рыночная стоимость выше
    восстановительной стоимости ее физических мощностей
  - Q := capitalization / (стоимость физических активов) >1
  - сигнальная роль цен акций: выгодно инвестировать в дорогие активы
- пузыри
  - рост цены на ожиданиях
  - $q_t = \sum_{s=1}^\infty \frac{1}{(1+r)^s} d_{t+s} + B_t$
  - пузырь $B_t$ - цена, отражающая ожидание роста цены со скоростью r
    - цена может быть любой - сигнальная функция цены исчезает
  - ложный сигнал инвесторам
    - инвестиции идут не туда, куда надо
    - рецессия после краха
    - финансовая система не выполняет свою фундаментальную функцию
- искаженные стимулы
  - крах 2008
    - секьюритизация
    - банки перестали кредитовать экономику, падение производства
    - упал спрос на товары
- инвестиции в плановой экономике
  - инвестиции шли не в рентабельные отрасли, а по идеологическим и
    политическим мотивам
    - тяжелая промышленность, ВПК
  - банкротство системы в конце 1980х
** Тест 6.
- 1 + x + x^2 + ... = S
  - x + x^2 + ... = Sx
  - (1-(1/(1+r))S = 1
  - S = 1+1/r
- Рассмотрим компанию «Final Exam Ltd.», которая функционирует на
  бесконечном временном горизонте. Известно, что по каждой акции
  данной компании в каждый период времени выплачивается фиксированный
  дивиденд в размере $7.5, а ставка процента постоянна и находится на
  уровне 15%. Кроме того, известно, что пузырь в цене акции «Final
  Exam Ltd.» отсутствует. Совокупное число выпущенных акций компании
  «Final Exam Ltd.» составляет 1000. Кроме того, восстановительная
  стоимость «Final Exam Ltd.» равна $40000. Чему равен показатель Q
  Тобина?
  - $7.5\sum_{k=1}^{\infty}\frac{1}{1.15^k}×1000 = \$50k$
  - Q = \frac{50}{40} = 1.25

* Тема 7: Денежный рынок и инфляция.
Седьмая тема курса посвящена денежному рынку и инфляции. Обсуждается,
как определяется денежная масса в экономике и к чему приводят ее
колебания.

- спрос на деньги
  - сколько население желает держать в ликвидной форме
  - M1 = наличные и счета до востребования
  - M2 = M1 + срочные счета + прочие депозиты
    - "денежная масса"
  - центральный банк выпускает денежную базу
  - наличные - самый невыгодный способ хранения средств
    - их держат как средство обмена
  - реальный спрос: деньги, выраженные в корзинах товаров M/P
    - реальная переменная
  - не хочется держать много денег, если
    - высокая инфляция
    - большая неопределенность
    - высокие (номинальные) процентные ставки
  - M/P = L(Y,i)
    - $i = r + \pi^e$ - реальная процентная ставка
      - r - реальная ставка
      - \pi^e - ожидаемая инфляция
  - _реальный_ спрос на деньги зависит от _номинальной_ ставки
    - инфляция одинакова для всех активов
- предложение денег
  - денежная база поставляется центробанком
    - ЦБ покупает у экономики в рамках денежной политики
      - гособлигации
      - валюту (скупка резервов)
    - ЦБ может также давать или брать в долг у частных банков
    - в принципе, ЦБ может купить что угодно и таким образом увеличить
      объем денег в экономике
  - затем банковская система производит еще деньги в процессе
    кредитования
    - M2 получается процессом мультпликацией
      - если мы положим ₽100 в банк, и банк обязан держать 10% в
        резервах
        - ₽100 денежной базы превращается в ₽100/(1-0.9) = ₽1000
          денежной массы
          - ₽1000/₽100 = 10 мультпликатор
  - мультипликатор m = M/B = (C+D)/(C+R) = (1+cr)/(cr+rr)
    - денежная масса M
    - наличные на руках C (cash)
    - резервы в банке R
    - cr = отношение наличных к вкладам = C/D
    - rr = отношение резервов к вкладам = R/D
  - правительство не может влиять на cr и rr
    - поэтому мультипликатор непостоянен
      - в России $\frac{M2}{M_{база}}$ ≅ 2
      - в США намного больше
    - например: падение мультипликатора с 3.7 в 1929 до 2.3 в 1933
      - за счет роста cr и rr
      - Friedman & Schwarz, A Monetary History of the United States
    - в 2008 мультипликатор упал с 9 до 4, но из-за увеличения
      денежной базы M2 остался постоянным
      - quantitative easing
- равновесие
  - за счет номинальной процентной ставки
    - если спрос больше предложеня, то население и банки берут в долг
      у ЦБ
      - денежная масса увеличивается, пока предложение не равно спросу
    - если же ЦБ фиксирует денежную массу, то подстроится номинальная
      ставка
    - график: i vs M
  - за счет фиксирования обменного курса
    - ЦБ продает или накапливает валютные запасы
    - ЦБ не может одновременно выбрать денежную массу и курс
      - одно выбирает ЦБ, другое - рынок
  - уровень цен
    - если население выбирает M/P, а ЦБ выбирает M, то рынок
      определяет P
    - количественная теория денег
      - уравнение обмена $M×V = P×Y$
        - V - скорость обращения денег (velocity of money)
        - P×Y - номинальный ВВП
          - те в равновесии денег тратится столько, сколько стоит
            годовой продукт
        - Y/V - спрос на деньги
      - Y и V _в долгосрочной перспективе_ растут независимо от M и P
        - примерно с постоянной скоростью
      - Увеличение M может повлиять только на P - т.е. на инфляцию
- инфляция
  - Милтон Фридман: инфляция всегда и везде есть денежное явление
    - инфляция происходит, когда денег больше чем требуется для
      экономики
    - большие колебания от квартала к кварталу
    - график: inflation rate vs money supply growth
  - сеньораж
    - если правительство не может собрать деньги налогами, оно их
      печатает
      - "инфляционный налог"
      - несправедливый, но его легко собрать
      - гиперифляция
  - реакция на ожидания
    - разделение на кратко- и долгосрочную перспективу
      - если ЦБ увеличит денежную массу однажды, то инфляцианные
        ожидания ведут к росту цен и зарплат
        - если ЦБ не оправдает ожидания, будет рецессия
  - чем плоха инфляция
    - издержки меню и стоптанных башмаков
    - изменчивость относительных цен при высокой инфляции усложняет
      принятие инвестиционных решений
    - высокая инфляция это непредсказуемая инфляция
      - добавляет большую премию за риск к процентным ставкам
  - польза от инфляции
    - проще подстраиваться относительным ценам
      - достаточно сохранить номинальные
      - "теория смазки"
    - реальные ставки могут опуститься ниже нуля
      - при дефляции 10% реальные ставки не могут быть ниже 10%
** Тест 7.
- В стране C сумма наличных на руках составляет 250 млрд рублей,
  резервы в банках – 50 млрд рублей, а сумма вкладов в банках – 250
  млрд рублей. Центральный банк данной страны решил увеличить
  количество денег в экономике. На выбор у него есть две опции:
  снизить норму обязательных резервов в два раза или совершить покупку
  государственных облигаций на вторичном рынке на сумму 30 млрд
  рублей. Определите, какая из двух опций приведет к большему
  увеличению денежной массы и в поле для ответа напишите, на сколько
  млрд рублей увеличится денежная масса по сравнению с первоначальной
  ситуацией в этом случае.
  - m = (C+D)/(C+R) = (250+250)/(250+50) = 5/3
  - 30×5/3 = 50

- Предложение денег в экономике страны D составляет $M^S = 300$, и
  центральный банк фиксирует ставку процента. Общий уровень цен
  неизменно равен 1. Спрос на деньги описывается уравнением $M/P =
  360 - 15i$ (ставка процента дана в процентных пунктах). В результате
  шока уравнение спроса на деньги приобретает вид $M/P = 400-15i$.
  1) Чему равна равновесная ставка процента?
     - 300/1 = 360 - 15i
       - i = 4% до шока
     - 300/1 = 400 - 15i
       - i = (20/3)% после шока
  2) На какую величину центральному банку необходимо увеличить
     предложение денег?
     - чтобы оставить i = 4%, M/1 = 400 - 15×4 = 400 - 60 = 340
* Тема 8: Отклонения от равновесия и экономический цикл.
Восьмая тема курса посвящена отклонениям экономики от равновесия и
экономическому циклу. Обсуждается, почему экономический рост идет
неравномерно – периоды роста сменяются спадами, после чего, как
правило, рост снова возобновляется. В данной теме рассматриваются
теории таких циклических колебаний, связанные с отклонениями от
классического рыночного равновесия.

- деловые циклы
  - нерегулярные колебания вокруг догосрочного тренда
  - в развитых странах цикл бум-рецессия-бум длится в среднем 6-8 лет
  - самый длинный период роста в США - 10 лет
  - Китай растет непрерывно с конца 1970-х
  - природа деловых циклов
    - классическая интерпретация
      - цикл = тренд
      - временные шоки производительности
    - кейнсианская интерпретация
      - цикл - отклонения от тренда
      - отклонения от общего равновесия
        - в результате несовершенств рынка и колебаний спроса
- факты о цикле
  - производительность проциклична
    - как труда, так и общефакторная
    - классическая интерпретация: производительность движет циклом
    - кейнсианская: во время бума капитал и трудовые ресурсы
      используются более эффективно
  - рабочая сила сильно проциклична
  - реальная зарплата слабо проциклична, почти ациклична
    - а может и нет: Барски, Паркер, Солон
      - во время бума нанимают работников с малой квалификацией
    - регулярным работникам платят больше
      - из зарплаты процикличны
  - инвестиции намного более волатильны, чем ВВП
    - самая волатильная компонента - накопление запасов
  - промышленное производство намного волатильней ВВП
    - статистика по промышленности собирается реже
    - сектор услуг более стабилен
  - потребление менее волатильно, чем ВВП
    - причинность? I и C движут циклом или наоборот?
  - денежная масса, цены и инфляция все процикличны
    - классики: во время бума спрос на деньги увеличивается
    - кейнсианцы/монетаристы: увеличение денежной массы в
      краткосрочной перспективе ведут к увеличению выпуска
- кейнсианская теория
  - продавцы редко меняют цены
    - почему? ведь фиксированная цена может быстро перестать быть
      оптимальной для продавца
      - он не хочет оставаться лоялным покупателям
      - он не знает, что оптимальная цена поменялась
      - прямые издержки от изменения цены
  - долго ли подстраиваются цены?
    - если цены меняются каждые полгода, придем ли мы к равновесию
      через полгода
    - продавцы меняют цены в разное время и не хотят сильно
      отклоняться друг от друга
    - стратегическое поведение - действия одного игрока зависят от
      дейтсвий других
- совокупное предложение
  - долгосрочное (LRAS, long-run aggregate supply): сколько экономика
    может произвести с нормальным использованием всех факторов
    - $Y^* = F(A,K,L)$
      - потенциальный ВВП
  - краткосрочное (SRAS)
    - сколько произвести по заранее объявленным ценам
- совокупный спрос (baby ISLM)
  - сколько товаров будет произведено при каждом уровне цен
    - Y = M×V/P
  - государство может повысить совокупный спрос
    - повысив расходы
    - напечатав деньги
    - понизив процентную ставку
  - частный сектор может повысить спрос при увелинии оптимизма
- график AS-AD (P vs Y)
  - SRAS подстраивается под пересечение AD и LRAS
- отклонение от равновесия - рецессия
  - упала уверенность в завтрашнем дне
  - потребители меньше покупают, инвесторы меньше инвестируют
    - V (спрос на деньги) падает
  - выпуск должен остаться неизменным, цены и зарплаты должны
    подстроиться, чтобы оставить Y постоянным
    - потребители меньше покупают ∴ цены падают ∴ больше сбережений ∴
      понизятся процентные ставки ∴ увеличиваются инвестиции ∴ валюта
      дешевеет ∴ экспорт вырастает
      - экономика сама себя вытягивает из рецессии
  - НО цены и зарплаты жесткие и не падают
    - потребители отказываются покупать по высоким ценам
      - сокращают инвестиции
    - фирмы увольняют работников
    - падают L, C, I, Y
      - экспорт растет (?)
    - график P vs Y
      - сдвиг AD влево
      - отрицательный разрыв выпуска
    - нужна стабилизационная политика правительства
- кризис 2007-2008
  - пузырь на рынке недвижимости
  - люди чувствовали себя богатыми, много тратили
  - инвестиции в недвижимость считались выгодными (Q Тобина > 1)
  - пузырь лопнул, цены упали
    - упали C и I
    - коммерческие банки стали сбрасывать активы и переходить в
      наличность
  - в России:
    - Банк России не хотел допустить падения рубля
      - чтобы спасти коммерческие банки
      - продавал доллары из резервов
        - денежная масса уменьшилась
      - опять падение спроса через несколько каналов

** Тест 8
- Рассмотрим экономику, которая описывается производственной функцией
  $Y = \sqrt{KL}. Функция спроса на рынке труда имеет вид $L^D = 149 -
  5w$, функция предложения труда – $L^S = 5w + 139$ ( w – реальная
  заработная плата). Запас капитала в экономике
  составляет 100. Уравнение совокупного спроса имеет вид $Y = 144 -
  8P$. Изначально выпуск находился на потенциальном уровне. В
  результате снижения уверенности инвесторов в завтрашнем дне
  уравнение совокупного спроса приняло вид $Y = 132 - 6P$.
  - Чему равен совокупный выпуск в экономике после шока в
    краткосрочном периоде (т.е. когда цены жесткие)?
    - L: 149 - 5w = 139 + 5w
      - w = 1
      - L = 144
    - $Y^* = \sqrt{100×144} = 10×12 = 120$ потенциальный выпуск
      - до шока, 120 = 144 - 8P, P = 24/8 = 3
    - P = 3, Y = 132 - 6P = 132 - 18 = 114
  - Чему равен совокупный выпуск в экономике после шока в долгосрочном
    периоде (т.е. когда цены подстроились)?
    - Y^* = 120$
  - Чему равен общий уровень цен после шока в долгосрочном периоде?
    - $Y^* = 120 = 132 - 6P$, $P = 2$

* Тема 9: Стабилизационная политика: денежная и бюджетная.
Девятая тема курса посвящена политике государства, направленной на
предотвращение или смягчение экономических спадов. Обсуждаются
механизмы и принципы денежной и бюджетной политик.

- фискальная политика:
  - увеличить G
    - New Deal
  - финансирование за счет бюджетного дефицита
  - проблемы
    - не хватает оперативности
      - трудно провести законы и внедрить все программы
    - волюнтаризм и коррупция
      - на что тратить деньги?
  - во время кризиса 2008-2009 гг бюджетная политика активно
    применялась
    - денежная политика уже использовалась по максимуму
      - ловушка ликвидности - процентная ставка не может опуститься
        ниже 0
- денежная политика
  - операции на открытом рынке: продажа/покупка гособлигаций на
    вторичном рынке
    - продает и покупает гособлигации по высокой цене
      - низкая доходность гос займа
      - привлекательность облигаций падает
        - они их продают и могут кредитовать население
      - ЦБ одновременно увеличил количество денег и уменьшил их
        стоимость
      - снизились краткосрочные процентные ставки
    - graph P vs Y (AD-AS)
      - кривая AD сдвинется на изначальную позицию
  - рефинансирование через дисконтное окно
    - кредитование последней инстанции
  - норма обязательных резервов - влияет на денежный мультипликатор
- шоки со стороны издержек
  - ожидание инфляции
    - профсоюзы заранее повышают зарплаты, производители - цены
    - потребление начинает падать, т.к. цены начинают расти
    - падает производство, т.к. зарплаты растут
    - падают инвестиции, т.к. поднимаются зарплаты и цены
    - инфляция становиться самореализующейся
    - P-Y graph
    - ЦБ может загасить саму инфляцию в ответ на ожидания
      - понизить процентные ставки, чтобы стимулировать C,I ?
        - увеличение денежной массы
          - оправдает инфляционные ожидания
        - долгосрочные процентные ставки повысятся еще сильнее
          - инвестиции еще сильнее упадут
      - надо лечить проблему _ожидания_ инфляции
        - ставки надо поднять и уменьшить денежную массу
        - усилит рецессию, но со временем процентные ставки упадут
          - возобновятся инвестиции
        - политически трудное решение
          - независимость ЦБ!
      - лучше всего не попадать в ситуацию инфляционных ожиланий
  - откуда берутся инфляционные ожидания
    - сам ЦБ создает их - динамическая непоследовательность
      - инфляция 1970х в США
        - кривая Филипса
        - экономику нельзя надолго вывести из равновесия
        - фиаско
          - только неожиданное повышение денежной массы может иметь
            реальный (временный) эффект
            - сколько раз можно это делать неожиданно?
          - ФРС потеряла контроль над инфляцией
      - У ЦБ всегда есть стимул неожиданно увеличить денежную
        массу
        - инфляционные ожидания рациональны!
        - всегда и везде должна ожидаться инфляция
        - Kydland and Prescott 1978
    - монотонная инфляция
      - P-Y graph
- оптимальная политика
  - формировать ожидания населения
  - обещать не печатать деньги и потом действительно их не печатать
  - но население знает, что ЦБ выгодно обмануть и напечатать деньги
  - независимый ЦБ
    - политика таргетирования инфляции
    - разница между равитыми и развивающимися странами
    - создание репутации
      - дезинфляция Пола Волкера 1980х
        - экономика ушла в самую глубокую рецессию со времен великой
          депрессии
          - изначально инфляцианные ожидания только повысилась из-за
            ожидания реакции на рецессию
        - инфляция была побеждена, но высокой ценой
  - правило Тэйлора (Taylor 1993)
    - реакция ставок на инфляцию должна быть больше, чем 1-1
      - надо повысить _реальные_ ставки
    - $i = 1\percent + 1.5 \pi^e + 50 \frac{Y-Y^*}{Y^*}%
  - таргетирование инфляции
    - инфляция сообщает, где находится $Y$ по отношению к $Y^*$
    - основная задача ЦБ
      - решение проблемы динамической непоследовательности
* Тема 10: Макроэкономическая политика в развивающихся странах и валютные кризисы.
Десятая неделя курса посвящена макроэкономической политике в
развивающихся странах. В данной теме рассматриваются проблемы, с
которыми более часто сталкиваются развивающиеся экономики:
стабилизация инфляции, валютные кризисы и внезапные развороты потоков
капитала.

- отличия развивающихся стран от развитых
  - высокая инфляция
  - большие колебания потоков капитала
    - внезапная остановка
  - валютные кризисы
- Цель политики в развитых странах
  - экономика в развитых странах оперирует на границе возможного
  - экономический рост происходит за счет НТП
    - не зависит от денежных властей
    - можно только уменьшить колебания и предотвратить "перегрев"
- цель политики в развивающихся странах
  - не используют все существующие возможности
    - современные технологии не используются
    - избыток рабсилы при недостатке капитала
  - надо достич границ возможностей
    - осмыслен ли термин "перегрев" для России и Китая?
    - нужно привлечь инвестиции
      - макроэкономическая стабильность
        - низкая и предсказуемая инфляция
        - отсутсвие больших колебаний обменных курсов
      - нет рисков дефолтов и кризисов
      - люди мало замечают стабильность, но очень хорошо замечают
        _нестабильность_
- политика фиксированного обменного курса
  - денежная политика в России
    - 1992-1994: период высокой инфляции
    - 1995-1998: период "валютного коридора"
      - фактически фиксированный курс
    - 1999-2008: управляемое плавание
      - формально гибкий, но сильно контролируется БР
    - 2009- : попытки перейти к таргетировния инфляции
  - ЦБ объявляет постоянный номинальный обменный курс
    - требуются значительные валютные резервы у ЦБ
  - разные степени жесткости
    - валютное управление (законодательно предписанный курс)
    - периодические интервенции
  - зачем фиксировать курс?
    - обеспечивает отсутсвие инфляционных колебаний
      - "номинальный якорь"
      - решает проблему динамической непоследовательности
      - денежная политика фактически передается другому ЦБ
    - уменьшение неопределенности в экономике
      - удорожание рубля ведет к уменьшению конкурентоспособности
        экспорта
      - удешевление рубля делает импортные факторы
      - финансовые потери ведут к падению инвестиций
      - при развитых финансовых рынках можно занять деньги
        - но в развивающихся странах плохо развиты финансовые рынки
  - минусы фиксированного курса
    - ЦБ лишается возможности проводить обменную политику
      - eg: рубль привязан к доллару, а ФРС повышает процентную ставку
        - капитал уходит в США
          - при свободном курсе доллар бы подорожал
          - при фиксированном, население меняет рубли на доллары
            - денежная масса сокращается, процентные ставки в России растут
              - а оно России в текущий момент нужно?
              - паритет процентных ставок
                - реальные процентные ставки должны быть одинаковыми (с
                  поправкой на риск)
    - гибкий обменный курс является естесвенным стабилизатором экономики
      - если рецессия,
        - спрос на заемные средства падает
        - падают процентные ставки
        - отток капитала
          - удешевление национальной валюты
            - стимулируется импортозамещение
            - рецессия смягчается
        - при фиксированном курсе, рецессия усиливается
          - как в России в 2008/9
- политика фиксированного курса часто приводит к валютному кризису
  - если фиксированный курс перестает соответсвовать рыночным реалиям
  - несоответсвие денежной политики политике фискального курса
  - доминирование фискальной политики денежной
  - eg: если одновременно поддерживать курс и печатать деньги
    - у населения все больше рублей, а импорт не дорожает
    - население начинает покупать доллары у ЦБ
      - пока они не закончатся
      - и тогда ЦБ отпускает курс
        - часто через мощную девальвацию
  - спекулятивная атака
    - "теневой" курс (который бы был без вмешательства ЦБ)
      - если "теневая" цена ниже официальной, они сбрасывают рубли
        - иначе они проиграют если "теневой" курс действительно
          установится
      - инвесторы сами провоцируют кризис
        - если ЦБ попытается защитить курс, он просто потратит все
          резервы
    - Paul Krugman 1979
    - как определить "теневой" курс?
      - достаточно даже ожиданий печатания денег
      - атака может произойти не тогда, когда деньги напечатаны, а
        когда рынок сочтет, что деньги печататься будут
- валютный кризис в России
  - неприятная монетаристская арифметика
  - Sargent & Wallace (1981)
  - _сокращение_ денежной массы может привести к инфляционным ожиданиям
    - предположим, что дефицит бюджета покрывается сеньоражем
    - чтобы бороться с инфляцией, правительство перестает печатать
      деньги и финансирует дефицит долгом
    - долг надо будет отдавать
      - для этого надо либо собрать налоги, либо опять печатать деньги
        - если население не верит в ликвидацию дефицита, оно ожидает
          сеньораж
  - нельзя сочетать жесткую денежную политику с мягкой бюджетной
    политикой
    - фискальное доминирование
    - невозможно бороться с инфляционными ожиданиями без
      сбалансированного бюджета
  - предистория российского кризиса
    - Sleifer & Treisman (2000)
    - лето 1992-го года: начало сеньоражной эмиссии
    - 1994-95: финансирование бюджета за счет заимствования
      - ГКО
      - одновременно ввели "валютный коридор"
      - в 1997м инфляция фиксируется на 11%
      - но дефициты остались
* ECON 102 essays
:LOGBOOK:
- Note taken on [2018-02-16 Fri 23:57] \\
  List of Topics for Cost Free Assignments (ECON 102)
  1. Many people believe that significant numbers of jobs in Canada
     have been outsourced to foreign countries. Describe how you would
     analyze the problem. (Hint: Has the amount of outsourcing by
     Canadian companies been significant relative to the size of our
     labour market/ what problems might you expect to encounter in
     carrying out your analysis?)
  2. In class, we have been saying for years before the base year,
     real GDP is greater than nominal GDP; and for years after the
     base year, nominal GDP is greater than real GDP. Suppose an
     economy experiences deflation, explain how will the relationship
     between nominal GDP and real GDP for years before and after the
     base year still hold or change.
  3. As of mid-2014, major banks in the US and Europe have been
     holding large amount of reserves. Use the money multiplier to
     explain how a reduction in reserves could lead to an increase in
     the money supply.
  4. Assume you are an owner of a Canadian firm in which your business
     mainly involves exporting and importing goods. Explain why you
     might prefer an exchange rate system like Bretton Woods (fixed
     system) rather than the current system (flexible system).
  5. Explain whether or how likely an economy will experience crowding
     out if the government runs a budget deficit. (Hint: “Austerity is
     pain. So is tight money,” Economists January 19, 2012)
  6. Using the concept of government spending multiplier, explain how
     the Japanese earthquake and tsunami of March 2011 may affect the
     Japanese economy as a whole. (Hint: “Japan says quake rebuilding
     to cost as much as 25tn yen,” BBC News, March 23, 2011)
  7. The text talks about the natural rate of unemployment is between
     6-7%. However, some evidence suggests the natural rate of
     unemployment may have increased after the recession of
     2008-2009. If the Bank of Canada believed that the natural rate
     was lower than it actually is, explain what would be the
     consequences for the Canadian economy.
  8. The IMF makes loans only to countries that are temporary running
     out of reserves of foreign currency. Explain how would such a
     loan helps a country to maintain a fixed exchange rate
     system. (Hint: why would a country have this temporary problem in
     the first place/ what must happen to the exchange rate if these
     problems persist rather than being temporary)
:END:
** Inflation is Caused by Too Many People Working
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [article,letterpaper,times,11pt,margin=0.7in]
#+LATEX_HEADER: \usepackage[margin=0.3in]{geometry}
- The text talks about the natural rate of unemployment is between
  6-7%. However, some evidence suggests the natural rate of
  unemployment may have increased after the recession of 2008-2009. If
  the Bank of Canada believed that the natural rate was lower than it
  actually is, explain what would be the consequences for the Canadian
  economy.

The mandate of the Bank of Canada is to ``regulate credit and currency
in the best interests of the economic life of the nation, to control
and protect the external value of the national monetary unit and to
mitigate by its influence fluctuations in the general level of
production, trade, prices and employment, so far as may be possible
within the scope of monetary action, and generally to promote the
economic and financial welfare of Canada"[fn::Bank of Canada Act
(R.S.C., 1985, c. B-2)]. In other words, the Bank of Canada is tasked
with determining and conducting fiscal policy with the purpose of maintaining
- the domestic economic output,
- employment,
- price level (i.e., containing inflation), and
- exchange rate with foreign currencies

Here, we shall focus on the first three objectives, in particular how,
according to the current theory, employment depends on the difference
between current and potential economic output, and the trade-off in
the short term between inflation and unemployment.

Let's start from afar: recall that the long-run aggregate supply or
potential GDP typically deviates from the actual output (or short-run
GDP); if we accept that the production is determined by the available
labour and capital (factories, roads, available computing power, cars,
etc) and write $Y=A\times F(L,K)$, where $K$ is the amount of capital,
$L$ the amount of labour, and $A$ the technological efficiency
parameter. Since $F$ is taken to be concave in $K$ --- diminishing
marginal returns on capital --- while depreciation rate $\delta$ is
constant, so that an amount $\delta K$ of capital is removed per unit
time, the Solow's model predicts that in the long run, the GDP per
capita will reach an equilibrium point, which is determined by the
ratio $\frac{\delta}{s}$ between the depreciation rate and investment
rate $s$. We'll need to keep in mind two features of the Solow's
model: first, in the developed countries, where the current GDP is
close to its potential value, we expect to see smaller GDP growth: the
model only gives us the option to increase $A$ through technological
advances and population growth. The developing countries, which are
still accumulating capital faster than it depreciates, should grow
faster. In both cases, the long-run aggregate supply to be perfectly
price-inelastic: the economy's potential output is independent of the
price level[fn::The fact that Solow's model exhibits monetary
neutrality isn't a revelation, it's a sanity check].

The short-run aggregate supply, on the other hand, is very
price-elastic: once the industial capacity is there, it can be
used. Labour, too, is often billed by the hour, and firms can reduce
the hours of their workers, or entice them to work overtime. A crucial
element in our model will be the dependence between the output, price
level, and the *expected* price level[fn::I am following closely
Chapter 13 of Mankiw, "Macroeconomics" 7th edition]. In the
`sticky-price' model, we suppose that not all firms can change prices
on the spot. If a firm can change its prices at will, let's express
its price policy $p$ as $p = P + a(Y-\bar{Y})$: the desired price
depends on the general price level and the level of aggregate
production. The firms with sticky prices will have to make a guess
about the expected price level $EP$ and set these prices now: for
them, $p=EP$. If the proportion of the firms with sticky prices is
$s$, then the overall price level will be the weighed average:
$P=s\timesEP + (1-s)\times(P+a(Y-\bar{Y}))$. Rearranging, we obtain
the SRAS equation with finite price elasticity:
$$Y-\bar{Y}=\alpha(P-EP)$$ where $\alpha=\frac{as}{1-s}>0$.

An alternative approach is imperfect-information model: even if
``markets clear" and the prices can adjust instantly depending on the
current level of output, the production decision a firm faces is based
on the expected relative price of the good compared to the prices of
all the other goods. The conclusion remains the same: the price level
depends on the _expected_ price level and the level of production
compared to its `natural' level.

We notice that we can temporarily boost production if the price level
turns out to be higher than expected. Of course, this cannot last
forever: the expectations about the prices will adjust, and the output
will return to its long-term value, at higher prices.

To return to the relationship between GDP and unemployment, it should
not be surprising to observe the empirical dependence between the
change in real GDP and unemployment rate[fn::Arthur M. Okun,
"Economics for Policymaking"]: employed workers contribute to
production of goods and services while unemployed ones do not. The
observation can be expressed as $\frac{Y-\bar{Y}}{\bar{Y}} = c
(u-\bar{u})$, with the constant $c$ measured to be about 2.

We now have all the ingridients to derive the equation for the
Philipps curve[fn::slight abuse of the language: strictly speaking,
there's no single Philipps curve] linking unemployment and inflation.
Rewrite the SRAS equation as $P=EP+\frac{Y-\bar{Y}}{\alpha}+v$, where
$v$ is exogenous supply shock such as a sudden change in commodity
prices. Inflation $\pi$ is just the difference in prices from the
previous period: $\pi=E-E_{-1}$, and similarly for the expected
inflation $E\pi$: $\pi=E\pi+\frac{Y-\bar{Y}}{\alpha}+v$. Finally,
substitute Okun's law to obtain $$\pi-E\pi=-\beta(u-\bar{u}) + v$$

We have derived that the inflation in the current period depends on
the the inflation in the past[fn::we're proxying the expected
inflation by the inflation in the past period], the cyclical
unemployment $(u-\bar{u})$, and a supply shock. For this reason, the
value $\bar{u}$ is named NAIRU, non-accelerating inflation rate of
unemployment. The crucial piece we had to rely on is price
`stickyness', which follows from at least two plausible models of firm
behaviour, and is supported by emprical evidence[fn::Alvarez et al,
"Sticky Prices in the Euro Area - a summary of new micro evidence" ECB
Working Paper Series no. 563 / December 2005]. It may therefore be
suprising that as late as mid-1990's, the NAIRU theory was not
universally accepted among the Governors of the US Federal
Reserve[fn::Laurence Meyer, "A Term at the Fed"], or indeed at the
Wall Street Journal, from which the title for this essay was
taken[fn::WSJ May 20, 1997, "The Meyer Fed? - WSJ"]. There are
plausible explanations for the existence of a non-zero NAIRU, such as
frictional and structural unemployment.

The NAIRU theory has enormous implications for the central banks:
first, it shows that the regulators can influence unemployment rate,
and could minimize it *if only they knew what value NAIRU actually is*
at any given time. The cost of using monetary policy to drive
unemployment lower than its `natural' rate is a higher rate of
inflation, which will propagate itself as *higher expectations of
inflation in the future*. This inflation ratcheting is referred to as
demand-pull inflation since it is driven by high aggregate demand,
which translates into higher wages, which in turn translate into
higher prices for goods and services. Unfortunately, the flip side is
that to reduce inflation, we either have to pray for a positive supply
shock[fn::so-called opportunistic disinflation], or be content to
lower GDP and thus raise unemployment rate in the future. The data
suggests the sacrifice ratio, the amount of production that has to be
forgone to lower inflation by 1 percentage point, has a rather painful
value of 5.

This is not to say all inflation is evil: a low value of 2-3% is
generally accepted as being beneficial for the economy, since it
exerts pressure on real wages and thus allows gradual reallocation of
workers to sectors with higher productivity. It also gives the central
banks freedom to lower real rates below 0%. Too high inflation
however, is considered harmful; it puts in jeopardy price stability (a
stated objective for the Bank of Canada). Again, while no-one can
predict what inflation level separates inflation from 'high, but ok'
from truly harmful, but expectations and precedent play an important
role: even concerns about /possibility/ of future inflation are enough
to panic investors and amplify uncertainty in the financial markets,
which can spill over to the real economy[fn::"Real Time Economics:
Inflation Worries Rattle Markets" WSJ 5 February 2018].

The naiive approach to NAIRU as a single Philipps curve which
constrains the inflation-unemployment tradeoff in the 1960s is widely
blamed for setting the stage for the double-digit inflation in the UK,
US, and Canada in the late 1970s: the lower unemployment rate was
bought at the expence of a higher inflation, which was pushed even
higher by the adverse supply shock of high oil prices. Once inflation
was perceived as too high, the regulators were under political
pressure to tighten monetary policy, incurring all the costs of high
unemployment rate while not achieving a return to 3% inflation until
the OPEC embargo was lifted in mid-1980s.

For the above reasons, most central banks now pursue inflation
targeting policy, aiming, in the case of Bank of Canada, for the 2% as
the mid-point of the 1%-3% inflation-control range[fn::Joint Statement
of the Government of Canada and the Bank of Canada on the Renewal of
the Inflation-Control Target, October 24, 1996]. If we suppose the
Bank of Canada underestimates the natural unemployment rate, it would
find it difficult to maintain its inflation target: the regulator
would be setting interest rate that is too low, causing wages and
prices to rise.

Of course we should ask ourselves the question how could the central
bank misjudge the NAIRU. By definition, it is the unemployment rate
which does not increase inflation, and is therefore an interpolated
metric. The lags in data reporting mean that NAIRU is not known at the
time, and the supply-shock term means that even in hindsight it may
not be possible to disentangle what NAIRU was[fn::Staiger et al, "How
Precise Are Estimates of the Natural Rate of Unemployment?"]. In
recent history, late 1990s were an unusually prosperous time in the
US, with both inflation and unemployment low by historical
standards. The explanation offered[fn::L Meyer, "A Term at the Fed"]
was a higher growth in productivity, which acted as a positive supply
shock, compounded by low prices of the imported goods due to
globalization - another positive supply shock. Similarly, in the even
more recent history, the oil price collapse of the 2014 can be viewed
as adverse supply shock which drastically lowered productivity in one
of Canada's core industries.

In conclusion, the NAIRU theory predicts that underestimating the
natural level of unemployment could cause the central bank to choose a
monetary policy that is too lax and ``cause the economy to overheat",
starting an inflation cycle that will not have lasting effects on
employment once the monetary stimulus is withdrawn.
*** Diagrams
      #+BEGIN_SRC latex :file tmp/inflation_ratcheting.pdf :packages '(("" "tikz")) :results raw
        \usetikzlibrary{decorations.pathreplacing}
        \begin{tikzpicture}[
            scale=5,
            axis/.style={very thick, ->, >=stealth'},
            important line/.style={thick},
            dashed line/.style={dashed, thin},
            pile/.style={thick, ->, >=stealth', shorten <=2pt, shorten
            >=2pt},
            every node/.style={color=black}
            ]
            % axes
            \draw[axis] (-0.1,0)  -- (1.1,0) node(xline)[right]
                {$I,S$};
            \draw[axis] (0,-0.1) -- (0,1.1) node(yline)[above] {$r$};
            % Lines
            \draw[important line] (.75,0.0) coordinate (A)
                               -- (.75,.85) coordinate (B)
                  node[centre, text width=8em] {$S=Y-(C+G)$};
            \draw[important line] (.05,.85) coordinate (C)
                               -- (.95,.05) coordinate (D)
                  node[right, text width=5em] {$I(r)$};
            \draw[dashed line]     (0,.6)   coordinate (E)
                                -- (1.,0.6) coordinate (F)
                  node[above, text width=5em] {$r^*$};
            % Intersection of lines
            \fill[red] (intersection cs:
               first line={(A) -- (B)},
               second line={(C) -- (D)}) coordinate (G) circle (.4pt)
               node[right,] {$r_{\rm closed}$};
            \fill[blue] (intersection cs:
               first line={(E) -- (F)},
               second line={(C) -- (D)}) coordinate (K) circle (0.3pt)
               node[above,] {$I(r^*)$};
            \fill[blue] (intersection cs:
               first line={(E) -- (F)},
               second line={(A) -- (B)}) coordinate (L) circle (0.3pt)
               node[below,] {$$};
            \draw [decorate, decoration={brace}, yshift=4ex] (K) --  node [above,] {NX} (L);
        \end{tikzpicture}
      #+END_SRC

      #+RESULTS:
      [[file:tmp/inflation_ratcheting.pdf]]

** Effects of Fiscal and Monetary Policies
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [article,letterpaper,times,11pt,margin=0.7in]
#+LATEX_HEADER: \usepackage[margin=0.3in]{geometry}
- Explain whether or how likely an economy will experience crowding
  out if the government runs a budget deficit. (Hint: “Austerity is
  pain. So is tight money,” Economists January 19, 2012)
- TL;DR: Increased government spending - indeed, any kind of
  expansionary fiscal policy - would cause pressure to crowd out,
  respectively, private investment in the case of a closed economy,
  and net exports, in the case of (small) open economy. Whether these
  pressures are realized as contraction in the corresponding sector
  depends on the coordination of the fiscal and monetary policies:
  expansionary monetary policy aimed at maintaining the money supply
  would alleviate the crowding-out effect and shift the
  aggregate-demand (AD herafter) curve to the right, both in closed
  and - to even greater extent - in an open economy. Standard Keynsian
  theory prescribes furthermore that, in times of recession,
  government spending, by supporting the aggregate demand, could well
  `crowd-in' additional private spending, particularly if coordinated
  with the monetary policy.
- Let us first lay down the context for our exposition: we will
  primarily focus on a situation where the domestic product has fallen
  below its `natural' or potential level due to lack of aggregate
  demand. This is a typical feature of a liquidity crisis; the real
  economy pays for the sins of the financial sector because lack of
  confidence leads to a fall in the money multiplier, which means
  lower money supply, hence higher interest rates, hence lower
  investment and therefore lower GDP. We should also stress that the
  human cost of fall in the output, for developed coutries, is
  primarily the rise in unemployment. If we express the functional
  dependency between the actual and potential output, on the one hand,
  and unemployment above the natural rate, as
  $\frac{Y-\bar{Y}}{\bar{Y}} = c (u-\bar{u})$[fn::note that this `gap
  form of Okun's Law' is not in itself particularly profound: an
  engineer may recognize it as first-order Taylor expanion of any
  functional dependency between $\Delta Y$ and $\Delta u$], the
  empirical evidence points to value of $c=2.5$[fn::Mankiw et
  al. "Macroeconomics", p.433]. In the words of Paul
  Krugman,[fn::Krugman, "The Accidental Theorist and Other Dispatches
  from the Dismal Science"] an unsold commodity is a nuisance, an
  unemployed worker a tragedy, so the governments understandably want
  to prop up aggregate demand when markets fail. The difference
  between classical and Keynsian models of economic rebound after a
  liquidity crisis is the speed with which prices and wages adapt to
  the reduced aggregate demand: Keynsians view prices as `sticky' in
  the short run, while the `freshwater' school of thought insists that
  markets should be able to adapt quickly, thus restoring the
  production output to pre-crisis levels without intervention - and
  any prolonged recessions must therefore have other underlying
  causes - for example, in the `monetarism' flavour, disbalance in the
  money supply. But regardless of whether they should or not, the
  govenments have two principal instruments to influence the economy:
  one is fiscal, the decision on what and how much to tax, and how
  much and where to spend the tax revenue, and the other is monetary,
  the decision to grow or contract the money supply.
- A budget deficit comes about if the government spending exceeds the
  taxes it collects. Whether the deficit arises by dint of spending
  more (most commonly, investment in infrastructure) or via tax breaks
  may well have a difference on the overall magnitude of boosting AD -
  depending on how government spending multiplier compares with that
  of the private sector, but the crowding-out effect is a primarily a
  monetary phenomenon, the root of which lies in the increased demand
  for liquidity, which, in the first instance, drives up the interest
  rate. In the case of an open economy with perfect capital mobility,
  the interest rate must equalize with the world prevailing rate,
  which is effected by appreciation of the dollar[fn::For brevity, we
  use 'dollar' as generic name of the local currency, and `Canada' for
  the home country.], which in turn crowds-out net exports by making
  the local production more expensive (and foreign cheaper), when
  calculated in foreign currency.  When the government enters the
  market to buy goods and services, it also enters the market for
  loanable funds, increasing the demand for money. The theory of
  liquidity preference predicts that the interest rate, which we could
  view as the price of tomorrow's money today, also increases. This
  makes borrowing money for building capital projects more costly, and
  hence hampers private investment. In effect, the government is
  daring to spend when and where private enterprise wouldn't --- with
  the concomitant risk that the expenditure would be worth it.
- The so-called 'treasury position', made infamous by the Winston
  Churchhill's budget speech of 1929[fn::Churchill, by his own
  admission, made a particularly poor Chancellor of the
  Exchequer][fn::The Economist August 11, 2016, "Where does the buck
  stop?"] is that private sector knows better than the government
  where capital investment is needed most, thus any stimulus package
  should favour tax cuts over spending. An even more extreme view is
  that the crowding-out of private investment balances the boost
  provided by the stimulus, making government intervention useless at
  best. A more extreme viewpoint still is that the rational
  expectations of the investors cancel out fiscal policy completely:
  the Ricardian equivalence principle of 'tax now or tax later' posits
  that since government debt has to be repaid eventually by increased
  tax revenue, rational firms and households would be indifferent
  between government deficit spending or higher taxes, proactively
  increasing savings in the former case.  The premise of the first
  assumption seems dubious to this author: government *can* be better
  at managing common goods[fn::they don't call it *tradegy* of the
  commons for nothing] like roads and fisheries, and many natural
  monopolies are best operated as public utilties. Why the
  crowding-out should balance or exceed the additional spending is not
  clear, even less clear is that the private sector would be prepared
  to spend *when* AD boost is needed most. Moreover, a boost in any
  spending, private or government, is enhanced by the so-called
  spending multiplier: just like in the fractional lending, a dollar
  in circulation is more than a dollar under the matress. In practical
  terms, a fraction of every dollar spent is being spent again by the
  entity who received it. Because the government has discretion on
  what to buy that is not dictated by the need to make profit, it can
  target spending in labor-intensive, low-productivity areas to make
  sure the money is converted to wages immediately, preferably for the
  lower-income workforce who would perforce spend most of it. If their
  marginal propensity to spend $\mu$ is large, the spending multiplier
  $\sum_{k=0}^\infty\mu^k = \frac{1}{1-\mu}$ is also large. Building
  roads and canals is looking better by the minute.
- If the economy is open, a higher interest rate cannot persist for
  long; it would have to equalize with the world prevailing rate. The
  mechanism by which this occurs is international market for goods and
  capital: foreign investors would be enticed to buy Canadian capital
  assets since they have a higher return than elsewhere. To buy said
  assets, they would first need to exchange their currency for the
  dollar, driving up the real exchange rate. Dollar-denominated
  exports would become more expensive and therefore less competitive;
  the exports are now being crowded out, and the fiscal policy does
  not appreciably change the aggregate demand.
- If the central bank coordinates monetary policy to expand the money
  supply at the same time as the government is increasing demand for
  loanable funds, the two pressures could balance each other so that
  the interest rate stays constant and no crowding out takes place.
- Moreover, in the 'neo-Keynsian' school, monetary policy is central
  and the central banks are the primary line of defence to stabilize
  the aggregate demand. Recognizing the argument that the market
  forces are, in general, best at maximizing welfare, the
  recommendation of the `saltwater' school is to try to replicate
  allocation of resources that emulates the situation where the prices
  _are_ flexible - by increasing the money supply and thus lowering
  the _real_ prices, even when they are sticky nominally. As a passing
  remark, exactly inability to increase money supply made Churchill's
  `treasury position' argument for his budget valid - but no less
  disastrous in achieving growth. He himself had put Britain on the
  gold standard in 1925, removing monetary policy as an option. For as
  long as the interest rate is above the lower bound of zero, monetary
  policy is to be tried first. In agreement with the classical theory,
  government spending should be set such that its marginal utility
  matches the marginal utility of private consumption[fn::Mankiw and
  Weinzierl 2011, An Exploration of Otimal Stabilization Policy]. Even
  once the lower bound of zero (`liquidity trap') is reached --- as it
  has been in the aftermath of the Great Recession of late 2000's,
  and, in Japan, since 1990's --- Mankiw and Weinzierl's model
  prescribes commitment to future expansionary monetary policy as the
  optimal response. Again, in agreement with the classical models, the
  fiscal policy is not to be used as a stabilization tool. Only when
  the commitment to a long-term expansionary policy is impossible ---
  and we'll discuss below why that may be so --- will Keynsian
  response become necessary.
- Unfortunately, the expansionary policies, continued to an extreme,
  would lead us to conclude that the 'Zimbabwe solution' of
  nationalizing industries and runaway printing of money is a viable
  way to sustain a high GDP. Of course the principle of monetary
  neutrality explicitly states that monetary policy has no effect on
  the GDP in the long term, while the government purchases, even if
  they can reproduce the same level of output short-term, cannot
  achieve the same *distribution* of production as the private sector,
  and hence could well impede long-term growth. If the expansionary
  monetary policy is not retracted in time, the inflationary price
  growth becomes expected, which neuteres the stimulus effect and sets
  up the stage for a painful disinflation in the future: if prices are
  expected to grow by 10% each year, the firms and workers will raise
  them in anticipation of this increase, and an expansion of the money
  supply by, say, 7% would have the same effect as contraction by
  3%. The central bank may be sorely tempted to print money even if it
  had committed itself previously to stop inflation. Similarly, a
  fiscal commitment to return to `small government' has to be credible
  to have crisis-fighting powers.
- So far, we have dealt with theories, which have to validated against
  empirical evidence. Unfortunately, empirical evidence is only
  available for the economic variables as they are[fn::more often, as
  they *were*] rather than for how they *could have been*, had
  alternative stabilization policy been chosen. The measure chosen to
  benchmark effect of a fiscal stimulus is the good ol' spending
  multiplier, a type of 'bang-for-buck' metric. Ironically, this
  Keynsian construct is most enthusiastically brandished by
  anti-Keynsians. Aside from wildly differing estimates[fn::just
  varying the time horizon for the autocorrelation model gives one
  enormous scope to confirm one's preferred theory] on the government
  multiplier obtained by various researchers, varying from negative to
  1.5[fn::Veldhuis et al, National Post 30 March 2010,
  "Harpernomics;..."], the multiplier completely ignores that even if
  a dollar spent by the government only increases the GDP by 50 cents,
  a dollar *not* spent by the government at the right time would have
  lowered the GDP by $1.50, which is what IMF seems to think of the
  austerity in the Eurozone[fn::Guajardo et al, IMF Working Paper
  2011, "Expansionary Austerity New International Evidence"]. An
  expansionary fiscal policy is the policy of last resort to be sure,
  and one that democratic governments may be loathe to undertake, but
  it may be the only way to recover from low aggregate demand caused
  by cash hoarding and deleveraging by the private sector, when the
  normally sound practice of thrift is hurting recovery by fallacy of
  composition[fn::Richard Koo, Centre for Economic Policy Research
  Policy Portal, 11 August 2014, Balance sheet recession is the reason
  for ‘secular stagnation'].
- In conclusion, there is a pressure for interest rates to increase if
  the government is running a deficit. The pressure comes from
  increased demand on the money supply. In a closed economy, the
  increased interest rate has the tendency to stifle private
  investment by making capital projects more expensive. In the
  presence of international trade and mobility of capital, the
  interest rate will equalize with the world prevailing rate by making
  the dollar more expensive, local production less competitive, and
  hence lowering net exports. The crowding-out of private investments
  or net exports counteracts the intended increase in the aggregate
  demand. Monetary policy however has the power to stop the
  crowding-out effect by expanding the money supply and preventing the
  exchange rate from rising, provided it is coordinated with the
  fiscal policy. An example of failure to coordinate government
  spending and monetary policy is Coney Crisis in the 1960's. In both
  neoclassical and neo-Keynsian models, monetary policy is the
  preferred option to deal with flagging aggregate demand in the short
  term, with the fiscal policy being a last resort when the central
  bank find itself in a liquidity trap of having reached zero lower
  bound for its interest rate.
* ECON 208 essay
:LOGBOOK:
- Note taken on [2018-07-19 Thu 14:48] \\
  Topics:
  - The future of the Canadian economy.
  - The three biggest challenges facing the Canadian economy.
  - The benefits and costs of the oil industry in the Alberta economy.
  - The effects of the influx of immigrants on the Canadian economy.
  - The best decisions are made at the margin. True or False.
  - Is pollution a failure of the market?
  - Do minimum wages help low-income workers?
:END:
** Are the Best Decisions Made at the Margin?
Let's consider an economy in which $10 is available for investment,
and the investment prospects have the following costs and returns:
| prospect | cost, $ | return, $ | return/cost    |
|----------+---------+-----------+----------------|
|        1 |       2 |         9 | $4\frac{1}{2}$ |
|        2 |       3 |        14 | $4\frac{2}{3}$ |
|        3 |       4 |        16 | $4$            |
|        4 |       6 |        30 | $5$            |

Suppose, for the moment, that we have a command economy, there is no
open market to allocate ressources. Instead, our task as a benevolent
dictator is to choose return-maximizing portfolio of investments,
while staying within the budget contraint. Importantly, a project
cannot be scaled down - pursuing it or not is an all-or-nothing
affair.[fn::Many models in economics, particularly at the macro level,
deal with quantities that are nearly infinitely divisible: with a
billion cars on the road in the world today, the fact that cars come
in integer quantities is immaterial. However, even for a nation-state
some undertakings come in discrete units: laying of capital ships,
launching sattelites, or high-speed rail links are some
examples. Projects on the scale of the Suez canal or the moonlanding
cannot yet be approximated by a continuous variable even globally]

With a 'marginalized' or /greedy/ approach, we would calculate 'bang
for buck' of each prospect, and fill the budget with the most
profitable prospects first. With repetition allowed (if a project can
be undertaken more than once), the solution we would obtain is this
way is projects #4 and #2, leaving $1 of budget unused, and returning
$30+$14=$44.

It is easy to see that projects #5 and #4 use the entire budget, and
return the total of $46. With repetitions allowed, we can do even
better: two counts of project #1 return the total of $18, so together
with project #6 we can achieve the total of $48.

The suboptimal greedy solution is *the solution that an open market
would achieve*, as long as each project is independent and no other
mechanism is available to solve the coordination problem.  Even if
someone decides to set up a synthetic project consisting of the
winning combination of the basic prospects, that would have the total
profitability of $\times 4.6$ (or $\times 4.8$, if repetitions
allowed). While better than any prospect other than #4, the market
would already choose #4, so the synthetic project would be no
different than #3[fn::or twice #1, with repetitions] by itself, which
looses to #2. Without arbitrage, there is nothing to force the optimal
solution on the macro scale.

If this example vindicates command economy, then only just: we took
the prices and returns as given. The 'killer feature' of an open
market is that it establishes relative prices efficiently. How would a
command economy do that?

/Linear programming/ is a standard approach: if there are $m$ factors
of production, the process of producing each of the $n$ goods the
economy is capable of is encoded as a linear combination of
inputs. For example, if the inputs are land and labor (in that order),
and the outputs are wheat and potatoes, then we can write
$$\left(\begin{matrix} 1 & 2 \\ 3 & 4 \end{matrix}\right)$$ to
indicate that, in order to produce one unit of wheat, one unit of
labor and two units of land are needed. Similarly, /activity vector/
$a_2$ for potatoes is $[3,4]$. If we wish to produce $x_1$ amount of
wheat and $x_2$ of potatoes, we would need to supply $x_1 (1,2)^T +
x_2 (3,4)^T = (x_1+3x_2,2x_1+4x_2)^T$, where the first component
represents the labor and the second the land requirement. As usual,
the resources are finite, and in general we have to maximize the
linear 'utility' function $\sum_i c_i x_i$, subject to constraints
$$\sum_j a_{ij} x_j \leq b_i \ 0\leq x_i \leq b_i$$ In our
wheat-and-potatoes example, we take that each unit of output of
e.g. wheat will bring $c_1$ worth of utility, and the limit on labour
is $b_1$. Unlike the classical production function, not every
combination of the input factors is possible, because the number of
possible ways to produce each good is finite (and is explicitly
enumerated in the /activity matrix/ above).

This model can be applied for managing production of a single firm
capable of producing multiple goods, in which case the coefficients
$c_i$ are simply prices[fn::we assume the firm a price taker,
operating under perfect competition], but also can describe the
economy as a whole, in which case the coefficients $c_i$ represent
some social value of the goods produced.

Having formulated the model as a linear programming problem, we can
take advantage of the general theory of LP, in particular the
remarkable fact that every LP maximization problem has a /dual/
minimization problem, which has the same solutions. The coefficients
of the dual problem have a natural interpretation as prices: in the
case of a firm, they would be treated as 'shadow' prices of the
resources, representing the profit the corresponding input factor can
contribute under the optimal production plan. In case of command
economy, the imputed prices are the prices a central planner would
assign since the open market mechanism is not available.

Let us consider an example linear program: maximize $x_1+6x_2$, with
constraints $$0 \leq x_1 \leq 200,\ 0\leq x_2 \leq 300, \ x_1+x_2 \leq
400$$  Adding the first inequality to the 6 times the second, we get
$x_1+6x_2 \leq 2000$, so the optimal solution is at
most 2000. Multiplying the second inequality by 5 and adding the third
gives an even better bound: $x_1 + 6x_2 \leq 1900$. In fact, it is
easy to verify that 1900 is indeed the solution to this problem. The
combination 0 times the first inequality, 5 times the second and 1
times the third is the solution to the dual problem: what combination
of multipliers for the original bounds produce the tightest upper
bound on the function to be maximized.

Now that we know how to assign prices to inputs in a command economy,
let's see if a decentralized decision making can still take place: can
ministers responsible for individual industries (which not only
compete for individual input factors but also can share production
facilities) make production decisions that combine to an optimal
allocation overall?

Well, if the imputed prices are calculated and promulgated, an
individual minister can calculate the cost of each good in his
portfolio, and compare to the final price $c_i$ for that
good[fn::again, this is either the 'social utility', or, in the case
of a firm under competition, the market price of the good]. In this
fashion, the losing production activities can be eliminated. The
problem now is that all the remaining activities will have price of
the good, as calculated on the basis of the shadow prices of the
factors exactly equal to the end price --- otherwise the shadow prices
are incorrect and should be higher[fn::Recall that the shadow prices
are constructed by reference to the most efficient processes producing
together the most valuable set of outputs]. So there is no mechanism
to coordinate the level of production of the goods that should be
produced, other than in the global context.  The maximization
principle globally to simply make sure all available inputs are
consumed, in the activities that are economical in the above sense.

There is of course another twist: if we again assume that only integer
amounts of inputs are possible, the LP problem now becomes an integer
programming problem, the solution to which can lie far away from the
LP optimum.

In summary, we considered some rather esoteric but hopefully not too
contrived examples in which optimizing utility requires coordination
on a larger scale and cannot be achieved by the 'local' consideration
of marginal gains.
